In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv("Absenteeism_preprocessed.csv")

In [3]:
data_preprocessed.describe(include = 'all')

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700,700,700,700,700.00000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.0,700.000000,700.000000,700.000000
unique,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,False,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,525,694,637,418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,6.36000,2.011429,222.347143,29.892857,36.417143,271.801774,26.737143,0.0,1.021429,0.687143,6.761429
std,NaN,NaN,NaN,NaN,3.50501,1.480396,66.312960,14.804446,6.379083,40.021804,4.254701,0.0,1.112215,1.166095,12.670082
min,NaN,NaN,NaN,NaN,1.00000,0.000000,118.000000,5.000000,27.000000,205.917000,19.000000,0.0,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,3.00000,1.000000,179.000000,16.000000,31.000000,241.476000,24.000000,0.0,0.000000,0.000000,2.000000
50%,NaN,NaN,NaN,NaN,6.00000,2.000000,225.000000,26.000000,37.000000,264.249000,25.000000,0.0,1.000000,0.000000,3.000000
75%,NaN,NaN,NaN,NaN,10.00000,3.000000,260.000000,50.000000,40.000000,294.217000,31.000000,0.0,2.000000,1.000000,8.000000
max,NaN,NaN,NaN,NaN,12.00000,6.000000,388.000000,52.000000,58.000000,378.884000,38.000000,0.0,4.000000,8.000000,120.000000

In [4]:
data_preprocessed.head()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [8]:
data_preprocessed['Excesive Absenteeism'] = targets

In [9]:
data_preprocessed.head()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excesive Absenteeism
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4,1
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2,0
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4,1
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2,0

In [10]:
targets.sum()/targets.shape[0]

np.float64(0.45571428571428574)

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day_of_Week', 'Daily Work Load Average', 'Distance to Work',], axis = 1)

In [12]:
data_with_targets.head()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excesive Absenteeism
0,False,False,False,True,7,289,33,30,0,2,1,1
1,False,False,False,False,7,118,50,31,0,1,0,0
2,False,False,False,True,7,179,38,31,0,0,0,0
3,True,False,False,False,7,279,39,24,0,2,0,1
4,False,False,False,True,7,289,33,30,0,2,1,0

In [13]:
data_with_targets is data_preprocessed

False

In [14]:
data_with_targets.iloc[:,:-1]

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,False,False,False,True,7,289,33,30,0,2,1
1,False,False,False,False,7,118,50,31,0,1,0
2,False,False,False,True,7,179,38,31,0,0,0
3,True,False,False,False,7,279,39,24,0,2,0
4,False,False,False,True,7,289,33,30,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,179,40,22,0,2,0
696,True,False,False,False,5,225,28,24,0,1,2
697,True,False,False,False,5,330,28,25,0,0,0
698,False,False,False,True,5,235,32,25,0,0,0
699,False,False,False,True,5,291,40,25,0,1,1

In [15]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

### standardize our data

In [16]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [17]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        # with some columns 'twist'
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns], axis=0)
        self.var_ = np.var(X[self.columns], axis=0)
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [18]:
unscaled_inputs.columns.values

array(['reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4',
       'Month', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [19]:
columns_to_scale = ['Month', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Children', 'Pets']

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,False,False,False,True,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,False,False,False,False,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,False,False,False,True,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,True,False,False,False,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,False,False,False,True,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,-0.388293,-0.654143,0.562059,-1.114186,0,0.880469,-0.589690
696,True,False,False,False,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,True,False,False,False,-0.388293,1.624567,-1.320435,-0.408580,0,-0.919030,-0.589690
698,False,False,False,True,-0.388293,0.190942,-0.692937,-0.408580,0,-0.919030,-0.589690
699,False,False,False,True,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [24]:
scaled_inputs.shape

(700, 11)

### slit the data into training and testing

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
train_test_split(scaled_inputs, targets)

[     reason_type_1  reason_type_2  reason_type_3  reason_type_4     Month  \
 178           True          False          False          False -0.959313
 271          False          False          False           True  0.753746
 587           True          False          False          False -1.244823
 86           False          False          False           True  1.324766
 130          False          False           True          False -1.530333
 ..             ...            ...            ...            ...       ...
 165           True          False          False          False -0.959313
 641          False          False          False           True -0.959313
 192          False          False          False           True -0.673803
 430          False          False          False           True -0.388293
 474          False          False          False           True  0.182726

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 178                0.040034 -1.320435        -0.643782          0 -0.019280
 271               -0.654143  0.248310         1.002633          0 -0.919030
 587                0.387122  1.660180         1.237836          0  0.880469
 86                -0.503235 -0.536062        -0.408580          0  0.880469
 130                1.005844 -0.536062         0.767431          0  0.880469
 ..                      ...       ...              ...        ...       ...
 165               -1.016322 -0.379188        -0.408580          0  0.880469
 641               -0.654143  0.248310         1.002633          0 -0.919030
 192               -1.574681  2.130803         1.002633          0 -0.019280
 430                2.092381 -1.320435         0.061825          0 -0.019280
 474                2.092381 -1.320435         0.061825          0 -0.019280

          Pets
 178  1.126663
 271 -0.589690
 587  0.268487
 86   1.126663
 130  0.268487
 ..        ...
 165 -0.589690
 641 -0.589690
 192 -0.589690
 430  2.843016
 474  2.843016

 [525 rows x 11 columns],
      reason_type_1  reason_type_2  reason_type_3  reason_type_4     Month  \
 621          False          False          False           True -0.959313
 152          False          False          False           True -1.244823
 523           True          False          False          False  1.039256
 87            True          False          False          False  1.324766
 329          False          False          False           True  1.324766
 ..             ...            ...            ...            ...       ...
 433           True          False          False          False -0.388293
 536           True          False          False          False  1.324766
 352           True          False          False          False  1.610276
 75            True          False          False          False  1.039256
 421          False          False          False           True -0.673803

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 621                0.387122  1.660180         1.237836          0  0.880469
 152                1.624567 -1.320435        -0.408580          0 -0.919030
 523                2.213108 -0.849811        -0.408580          0  1.780219
 87                 1.036026  0.562059        -0.408580          0 -0.019280
 329               -0.654143  0.248310         1.002633          0 -0.919030
 ..                      ...       ...              ...        ...       ...
 433               -0.654143  0.562059        -1.114186          0  0.880469
 536               -1.574681  0.091435         0.297027          0 -0.919030
 352                0.190942  1.032682         2.649049          0 -0.019280
 75                 1.036026  0.562059        -0.408580          0 -0.019280
 421                1.171843  1.032682        -0.408580          0  0.880469

          Pets
 621  0.268487
 152 -0.589690
 523 -0.589690
 87   0.268487
 329 -0.589690
 ..        ...
 433 -0.589690
 536 -0.589690
 352 -0.589690
 75   0.268487
 421  0.268487

 [175 rows x 11 columns],
 array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
        0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1]),
 array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1])]

In [27]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets,train_size = 0.8, random_state = 20)

In [28]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 11) (560,)
(140, 11) (140,)

## Logistic Regression with Sklearn

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Train the model

In [30]:
reg = LogisticRegression()

In [31]:
reg.fit(x_train, y_train)

LogisticRegression()

In [32]:
reg.score(x_train, y_train)

0.7785714285714286

In [33]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [34]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [35]:
model_output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True, False,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [36]:
np.sum(model_output == y_train)

np.int64(436)

In [37]:
y_train.shape[0]

560

In [38]:
np.sum(model_output == y_train)/y_train.shape[0]

np.float64(0.7785714285714286)

# finding the intercept and the coefficient

In [39]:
reg.intercept_

array([-1.69032199])

In [40]:
reg.coef_

array([[ 2.79957484,  0.91304005,  3.09125908,  0.85362484,  0.16418968,
         0.6012604 , -0.16717696,  0.30783491,  0.        ,  0.36473108,
        -0.2697601 ]])

In [41]:
unscaled_inputs.columns.values

array(['reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4',
       'Month', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [42]:
feature_names = unscaled_inputs.columns.values

In [43]:
summary_table = pd.DataFrame(columns=['feature_names'], data = feature_names)
summary_table['coefficients'] = np.transpose(reg.coef_)
summary_table

             feature_names  coefficients
0            reason_type_1      2.799575
1            reason_type_2      0.913040
2            reason_type_3      3.091259
3            reason_type_4      0.853625
4                    Month      0.164190
5   Transportation Expense      0.601260
6                      Age     -0.167177
7          Body Mass Index      0.307835
8                Education      0.000000
9                 Children      0.364731
10                    Pets     -0.269760

In [44]:
summary_table.index = summary_table.index + 1

In [45]:
summary_table.loc[0] = ['intercept', reg.intercept_[0]]

In [46]:
summary_table = summary_table.sort_index()
summary_table

             feature_names  coefficients
0                intercept     -1.690322
1            reason_type_1      2.799575
2            reason_type_2      0.913040
3            reason_type_3      3.091259
4            reason_type_4      0.853625
5                    Month      0.164190
6   Transportation Expense      0.601260
7                      Age     -0.167177
8          Body Mass Index      0.307835
9                Education      0.000000
10                Children      0.364731
11                    Pets     -0.269760

# interpreting the coefficients

In [47]:
summary_table['odds_ratio'] = np.exp(summary_table.coefficients)

In [48]:
summary_table

             feature_names  coefficients  odds_ratio
0                intercept     -1.690322    0.184460
1            reason_type_1      2.799575   16.437657
2            reason_type_2      0.913040    2.491886
3            reason_type_3      3.091259   22.004766
4            reason_type_4      0.853625    2.348143
5                    Month      0.164190    1.178438
6   Transportation Expense      0.601260    1.824417
7                      Age     -0.167177    0.846050
8          Body Mass Index      0.307835    1.360476
9                Education      0.000000    1.000000
10                Children      0.364731    1.440127
11                    Pets     -0.269760    0.763563

In [49]:
summary_table.sort_values('odds_ratio', ascending = False)

             feature_names  coefficients  odds_ratio
3            reason_type_3      3.091259   22.004766
1            reason_type_1      2.799575   16.437657
2            reason_type_2      0.913040    2.491886
4            reason_type_4      0.853625    2.348143
6   Transportation Expense      0.601260    1.824417
10                Children      0.364731    1.440127
8          Body Mass Index      0.307835    1.360476
5                    Month      0.164190    1.178438
9                Education      0.000000    1.000000
7                      Age     -0.167177    0.846050
11                    Pets     -0.269760    0.763563
0                intercept     -1.690322    0.184460

### testing

In [50]:
reg.score(x_test, y_test)

0.75

In [53]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71534448, 0.28465552],
       [0.59609394, 0.40390606],
       [0.42788316, 0.57211684],
       [0.78524649, 0.21475351],
       [0.08644793, 0.91355207],
       [0.34311501, 0.65688499],
       [0.30624628, 0.69375372],
       [0.13293204, 0.86706796],
       [0.79450288, 0.20549712],
       [0.75194182, 0.24805818],
       [0.49726505, 0.50273495],
       [0.23005601, 0.76994399],
       [0.07524016, 0.92475984],
       [0.69217496, 0.30782504],
       [0.32559666, 0.67440334],
       [0.51292061, 0.48707939],
       [0.55563097, 0.44436903],
       [0.54402847, 0.45597153],
       [0.41514668, 0.58485332],
       [0.05495753, 0.94504247],
       [0.70754838, 0.29245162],
       [0.78524649, 0.21475351],
       [0.43045433, 0.56954567],
       [0.43045433, 0.56954567],
       [0.26386362, 0.73613638],
       [0.75359817, 0.24640183],
       [0.51958066, 0.48041934],
       [0.84214497, 0.15785503],
       [0.21145959, 0.78854041],
       [0.78524649, 0.21475351],
       [0.64031396, 0.35968604],
       [0.33460703, 0.66539297],
       [0.32230505, 0.67769495],
       [0.47385001, 0.52614999],
       [0.78524649, 0.21475351],
       [0.4654907 , 0.5345093 ],
       [0.78674353, 0.21325647],
       [0.27759478, 0.72240522],
       [0.58961037, 0.41038963],
       [0.39846906, 0.60153094],
       [0.79304598, 0.20695402],
       [0.52581387, 0.47418613],
       [0.77059098, 0.22940902],
       [0.60868231, 0.39131769],
       [0.16991889, 0.83008111],
       [0.45099291, 0.54900709],
       [0.31897307, 0.68102693],
       [0.71534448, 0.28465552],
       [0.79355479, 0.20644521],
       [0.80063412, 0.19936588],
       [0.39835877, 0.60164123],
       [0.64041695, 0.35958305],
       [0.34311501, 0.65688499],
       [0.74368699, 0.25631301],
       [0.17411579, 0.82588421],
       [0.57333239, 0.42666761],
       [0.12267839, 0.87732161],
       [0.77457599, 0.22542401],
       [0.65856082, 0.34143918],
       [0.64794298, 0.35205702],
       [0.27403447, 0.72596553],
       [0.35375698, 0.64624302],
       [0.71221951, 0.28778049],
       [0.22090987, 0.77909013],
       [0.7961838 , 0.2038162 ],
       [0.73404438, 0.26595562],
       [0.91962057, 0.08037943],
       [0.78674353, 0.21325647],
       [0.29087324, 0.70912676],
       [0.6508542 , 0.3491458 ],
       [0.78674353, 0.21325647],
       [0.72741549, 0.27258451],
       [0.09251377, 0.90748623],
       [0.53194792, 0.46805208],
       [0.39663072, 0.60336928],
       [0.78524649, 0.21475351],
       [0.23585932, 0.76414068],
       [0.23459929, 0.76540071],
       [0.2739875 , 0.7260125 ],
       [0.33830124, 0.66169876],
       [0.76219899, 0.23780101],
       [0.92432714, 0.07567286],
       [0.77457599, 0.22542401],
       [0.25684282, 0.74315718],
       [0.57259684, 0.42740316],
       [0.86550501, 0.13449499],
       [0.30217661, 0.69782339],
       [0.43045433, 0.56954567],
       [0.76780584, 0.23219416],
       [0.33460703, 0.66539297],
       [0.80077319, 0.19922681],
       [0.85317306, 0.14682694],
       [0.77723563, 0.22276437],
       [0.73404438, 0.26595562],
       [0.75194182, 0.24805818],
       [0.15708538, 0.84291462],
       [0.70570335, 0.29429665],
       [0.24351256, 0.75648744],
       [0.76956457, 0.23043543],
       [0.75210434, 0.24789566],
       [0.3744251 , 0.6255749 ],
       [0.33460703, 0.66539297],
       [0.32298319, 0.67701681],
       [0.22994221, 0.77005779],
       [0.54359993, 0.45640007],
       [0.50855177, 0.49144823],
       [0.72479294, 0.27520706],
       [0.15708538, 0.84291462],
       [0.19971421, 0.80028579],
       [0.85894871, 0.14105129],
       [0.93062967, 0.06937033],
       [0.09754189, 0.90245811],
       [0.36347791, 0.63652209],
       [0.6720255 , 0.3279745 ],
       [0.47717107, 0.52282893],
       [0.44414979, 0.55585021],
       [0.22483824, 0.77516176],
       [0.17701299, 0.82298701],
       [0.46100561, 0.53899439],
       [0.69775476, 0.30224524],
       [0.74309506, 0.25690494],
       [0.82253852, 0.17746148],
       [0.19117646, 0.80882354],
       [0.52581387, 0.47418613],
       [0.78524649, 0.21475351],
       [0.5958992 , 0.4041008 ],
       [0.79304598, 0.20695402],
       [0.89423322, 0.10576678],
       [0.26415849, 0.73584151],
       [0.70754838, 0.29245162],
       [0.38728812, 0.61271188],
       [0.79304598, 0.20695402],
       [0.70570335, 0.29429665],
       [0.5958992 , 0.4041008 ],
       [0.74016407, 0.25983593],
       [0.47717107, 0.52282893],
       [0.54402847, 0.45597153],
       [0.64012767, 0.35987233],
       [0.76956457, 0.23043543],
       [0.53194792, 0.46805208]])

In [54]:
predicted_proba.shape

(140, 2)

In [55]:
predicted_proba[:,1]

array([0.28465552, 0.40390606, 0.57211684, 0.21475351, 0.91355207,
       0.65688499, 0.69375372, 0.86706796, 0.20549712, 0.24805818,
       0.50273495, 0.76994399, 0.92475984, 0.30782504, 0.67440334,
       0.48707939, 0.44436903, 0.45597153, 0.58485332, 0.94504247,
       0.29245162, 0.21475351, 0.56954567, 0.56954567, 0.73613638,
       0.24640183, 0.48041934, 0.15785503, 0.78854041, 0.21475351,
       0.35968604, 0.66539297, 0.67769495, 0.52614999, 0.21475351,
       0.5345093 , 0.21325647, 0.72240522, 0.41038963, 0.60153094,
       0.20695402, 0.47418613, 0.22940902, 0.39131769, 0.83008111,
       0.54900709, 0.68102693, 0.28465552, 0.20644521, 0.19936588,
       0.60164123, 0.35958305, 0.65688499, 0.25631301, 0.82588421,
       0.42666761, 0.87732161, 0.22542401, 0.34143918, 0.35205702,
       0.72596553, 0.64624302, 0.28778049, 0.77909013, 0.2038162 ,
       0.26595562, 0.08037943, 0.21325647, 0.70912676, 0.3491458 ,
       0.21325647, 0.27258451, 0.90748623, 0.46805208, 0.60336928,
       0.21475351, 0.76414068, 0.76540071, 0.7260125 , 0.66169876,
       0.23780101, 0.07567286, 0.22542401, 0.74315718, 0.42740316,
       0.13449499, 0.69782339, 0.56954567, 0.23219416, 0.66539297,
       0.19922681, 0.14682694, 0.22276437, 0.26595562, 0.24805818,
       0.84291462, 0.29429665, 0.75648744, 0.23043543, 0.24789566,
       0.6255749 , 0.66539297, 0.67701681, 0.77005779, 0.45640007,
       0.49144823, 0.27520706, 0.84291462, 0.80028579, 0.14105129,
       0.06937033, 0.90245811, 0.63652209, 0.3279745 , 0.52282893,
       0.55585021, 0.77516176, 0.82298701, 0.53899439, 0.30224524,
       0.25690494, 0.17746148, 0.80882354, 0.47418613, 0.21475351,
       0.4041008 , 0.20695402, 0.10576678, 0.73584151, 0.29245162,
       0.61271188, 0.20695402, 0.29429665, 0.4041008 , 0.25983593,
       0.52282893, 0.45597153, 0.35987233, 0.23043543, 0.46805208])

### save the model

In [56]:
import pickle

In [57]:
with open('model', 'wb') as file:
    pickle.dump(reg,file)

In [59]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)