In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Absenteeism_data.csv')

In [3]:
data.describe(include = 'all')

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700.000000,700.000000,700,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
unique,NaN,NaN,432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,17/08/2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,17.951429,19.411429,NaN,222.347143,29.892857,36.417143,271.801774,26.737143,1.282857,1.021429,0.687143,6.761429
std,11.028144,8.356292,NaN,66.312960,14.804446,6.379083,40.021804,4.254701,0.668090,1.112215,1.166095,12.670082
min,1.000000,0.000000,NaN,118.000000,5.000000,27.000000,205.917000,19.000000,1.000000,0.000000,0.000000,0.000000
25%,9.000000,13.000000,NaN,179.000000,16.000000,31.000000,241.476000,24.000000,1.000000,0.000000,0.000000,2.000000
50%,18.000000,23.000000,NaN,225.000000,26.000000,37.000000,264.249000,25.000000,1.000000,1.000000,0.000000,3.000000
75%,28.000000,27.000000,NaN,260.000000,50.000000,40.000000,294.217000,31.000000,1.000000,2.000000,1.000000,8.000000
max,36.000000,28.000000,NaN,388.000000,52.000000,58.000000,378.884000,38.000000,4.000000,4.000000,8.000000,120.000000

In [4]:
raw_data = data.drop(['ID'], axis = 1)

In [5]:
raw_data

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [6]:
raw_data.describe()

,Reason for Absence,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
mean,19.411429,222.347143,29.892857,36.417143,271.801774,26.737143,1.282857,1.021429,0.687143,6.761429
std,8.356292,66.312960,14.804446,6.379083,40.021804,4.254701,0.668090,1.112215,1.166095,12.670082
min,0.000000,118.000000,5.000000,27.000000,205.917000,19.000000,1.000000,0.000000,0.000000,0.000000
25%,13.000000,179.000000,16.000000,31.000000,241.476000,24.000000,1.000000,0.000000,0.000000,2.000000
50%,23.000000,225.000000,26.000000,37.000000,264.249000,25.000000,1.000000,1.000000,0.000000,3.000000
75%,27.000000,260.000000,50.000000,40.000000,294.217000,31.000000,1.000000,2.000000,1.000000,8.000000
max,28.000000,388.000000,52.000000,58.000000,378.884000,38.000000,4.000000,4.000000,8.000000,120.000000

In [7]:
dummies = pd.get_dummies(raw_data['Reason for Absence'],drop_first = True)

In [8]:
dummies

,1,2,3,4,5,6,7,8,9,10,...,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
696,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
697,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
698,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [9]:
reason_type_1 = dummies.loc[:, '1':'14'].max(axis=1)
reason_type_2 = dummies.loc[:, '15':'17'].max(axis=1)
reason_type_3 = dummies.loc[:, '18':'21'].max(axis=1)
reason_type_4 = dummies.loc[:, '22':].max(axis=1)

In [10]:
reason_type_2

0      False
1      False
2      False
3      False
4      False
       ...
695    False
696    False
697    False
698    False
699    False
Length: 700, dtype: bool

In [11]:
df = pd.concat([raw_data, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis=1)

In [12]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours', 0, 1, 2, 3], dtype=object)

In [13]:
columns_names = ['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours','reason_type_1','reason_type_2','reason_type_3','reason_type_4']

In [14]:
df.columns = columns_names
df

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,reason_type_1,reason_type_2,reason_type_3,reason_type_4
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4,False,False,False,True
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0,False,False,False,False
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4,True,False,False,False
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,40,237.656,22,2,2,0,8,True,False,False,False
696,6,23/05/2018,225,26,28,237.656,24,1,1,2,3,True,False,False,False
697,10,24/05/2018,330,16,28,237.656,25,2,0,0,8,True,False,False,False
698,23,24/05/2018,235,16,32,237.656,25,3,0,0,2,False,False,False,True
699,28,31/05/2018,291,31,40,237.656,25,1,1,1,2,False,False,False,True

In [15]:
columns_names_reordered = ['reason_type_1','reason_type_2','reason_type_3','reason_type_4','Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours']
df = df[columns_names_reordered]
df.head()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [16]:
data_with_dummies = df.drop(['Reason for Absence'], axis = 1)

In [17]:
data_with_dummies

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,True,False,False,False,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,True,False,False,False,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,False,False,False,True,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,False,False,False,True,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [18]:
data_with_dummies['Date'] = pd.to_datetime(data_with_dummies['Date'], dayfirst=True)
data_with_dummies['Month'] = data_with_dummies['Date'].dt.month       
data_with_dummies['Day_of_Week'] = data_with_dummies['Date'].dt.dayofweek   
data_with_dummies = data_with_dummies.drop(columns=['Date'])

In [19]:
data_with_dummies

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month,Day_of_Week
0,False,False,False,True,289,36,33,239.554,30,1,2,1,4,7,1
1,False,False,False,False,118,13,50,239.554,31,1,1,0,0,7,1
2,False,False,False,True,179,51,38,239.554,31,1,0,0,2,7,2
3,True,False,False,False,279,5,39,239.554,24,1,2,0,4,7,3
4,False,False,False,True,289,36,33,239.554,30,1,2,1,2,7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,179,22,40,237.656,22,2,2,0,8,5,2
696,True,False,False,False,225,26,28,237.656,24,1,1,2,3,5,2
697,True,False,False,False,330,16,28,237.656,25,2,0,0,8,5,3
698,False,False,False,True,235,16,32,237.656,25,3,0,0,2,5,3
699,False,False,False,True,291,31,40,237.656,25,1,1,1,2,5,3

In [20]:
data_with_dummies['Education'] = data_with_dummies['Education'].map(lambda x: 1 if x == 0 else 0)

In [21]:
data_with_dummies

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month,Day_of_Week
0,False,False,False,True,289,36,33,239.554,30,0,2,1,4,7,1
1,False,False,False,False,118,13,50,239.554,31,0,1,0,0,7,1
2,False,False,False,True,179,51,38,239.554,31,0,0,0,2,7,2
3,True,False,False,False,279,5,39,239.554,24,0,2,0,4,7,3
4,False,False,False,True,289,36,33,239.554,30,0,2,1,2,7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,179,22,40,237.656,22,0,2,0,8,5,2
696,True,False,False,False,225,26,28,237.656,24,0,1,2,3,5,2
697,True,False,False,False,330,16,28,237.656,25,0,0,0,8,5,3
698,False,False,False,True,235,16,32,237.656,25,0,0,0,2,5,3
699,False,False,False,True,291,31,40,237.656,25,0,1,1,2,5,3

In [22]:
data_with_dummies.columns.values

array(['reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month',
       'Day_of_Week'], dtype=object)

In [24]:
columns_names_updated = ['reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4', 'Month','Day_of_Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']
data_with_dummies = data_with_dummies[columns_names_updated]
data_with_dummies.head()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2

In [25]:
data_with_dummies.copy()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,2,179,22,40,237.656,22,0,2,0,8
696,True,False,False,False,5,2,225,26,28,237.656,24,0,1,2,3
697,True,False,False,False,5,3,330,16,28,237.656,25,0,0,0,8
698,False,False,False,True,5,3,235,16,32,237.656,25,0,0,0,2
699,False,False,False,True,5,3,291,31,40,237.656,25,0,1,1,2

In [27]:
data_with_dummies.to_csv('Absenteeism_preprocessed.csv', index=False)

In [28]:
data = pd.read_csv('Absenteeism_preprocessed.csv')

In [29]:
data

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,2,179,22,40,237.656,22,0,2,0,8
696,True,False,False,False,5,2,225,26,28,237.656,24,0,1,2,3
697,True,False,False,False,5,3,330,16,28,237.656,25,0,0,0,8
698,False,False,False,True,5,3,235,16,32,237.656,25,0,0,0,2
699,False,False,False,True,5,3,291,31,40,237.656,25,0,1,1,2